### ISSUE TITLE
Terraform Version Update

### ISSUE THREAD

**Issue by AlexAtkinson** [infrablocks/terraform-aws-organization#30]
Please update the tf version. As it is the lifecycle block cannot be used, which causes issues with 'aws_service_access_principals'.

"The block type name "lifecycle" is reserved for use by Terraform in a future version."

**Comment by tobyclemson** [comment]
Hey @AlexAtkinson, 

I'll try and have a look at this this week but would also accept a PR if you have the time. I think all that's needed is changing `"~> 3.33"` to `">= 3.33"` in `terraform.tf`.

Thanks,
Toby

**Comment by tobyclemson** [comment]
This has been fixed in version [1.1.0](https://registry.terraform.io/modules/infrablocks/organization/aws/1.1.0).

Thanks,
Toby
