### ISSUE TITLE
Provide input for 'aws_service_access_principals'

### ISSUE THREAD

**Issue by AlexAtkinson** [infrablocks/terraform-aws-organization#31]
Please provide an input for setting 'aws_service_access_principals'.

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/config_organization_conformance_pack

Thanks.

**Comment by tobyclemson** [comment]
Hey @AlexAtkinson,

Thanks for raising, I'll try and have a look this week. Also happy for a PR if you have time.

Thanks,
Toby

**Comment by tobyclemson** [comment]
I see there's actually another PR open for this so I'll prioritise it for this week.

**Comment by tobyclemson** [comment]
This has been fixed in version [1.1.0](https://registry.terraform.io/modules/infrablocks/organization/aws/1.1.0).

Thanks,
Toby
